#!/lib/superatmos/root/busybox sh
if /lib/superatmos/root/busybox [ $# -lt 1 ];
then
  /system/bin/getprop
  for i in $(/lib/superatmos/root/busybox ls -1 /customkernel/property/*); do
    j=$(echo "$i" | cut -d "/" -f 4)
    k=$(cat $i);
    echo [$j]: [$k];
  done;
else
  if /lib/superatmos/root/busybox [ -f /customkernel/property/$1 ];
  then
    cat /customkernel/property/$1
  else
    /system/bin/getprop "$@"
  fi;
fi;